////
////  VerificationCodeViewController.swift
////  GoFixCustomer
////
////  Created hieu nguyen on 7/12/18.
////  Copyright © 2018 gofix.vinova.sg. All rights reserved.
////
////  Template generated by Juanpe Catalán @JuanpeCMiOS
////
//
//import UIKit
//
//class VerificationCodeViewController: UIViewController, VerificationCodeViewProtocol {
//
//	var presenter: VerificationCodePresenterProtocol?
//    @IBOutlet weak var stackViewCodeTxt: UIStackView!
//    @IBOutlet weak var resendBtn: UIButton!
//    @IBOutlet weak var phoneNumbLbl: UILabel!
//    
//	override func viewDidLoad() {
//        super.viewDidLoad()
//        
//        title = Strings.VerificationCode.navTitle
//        setupView()
//    }
//    
//    private func setupView() {
//        // custom resend button
//        resendBtn.setBorder(borderWidth: 1.0, borderColor: Color.orangeGofix, cornerRadius: 1.5)
//        resendBtn.tintColor = Color.orangeGofix
//        
//        //
//        stackViewCodeTxt.arrangedSubviews.forEach {
//            ($0 as! VerificationTextField).delegate = self
//            ($0 as! VerificationTextField).handleKeyboardDelegate = self
//        }
//        //
//        guard let firstTxtField = stackViewCodeTxt.arrangedSubviews.first else { return }
//        firstTxtField.becomeFirstResponder()
//    }
//    
//    var currChar: String?
//    var currTxtIndex: Int = 0
//}
//
//extension VerificationCodeViewController: UITextFieldDelegate, VerificationTextFieldDelegate {
//    func textFieldDidDelete(in textField: VerificationTextField) {
//        clearTextField(tfIndex: textField.tag-1)
//    }
//    
//    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
//        let previousString = textField.text!
//        let txtTag = textField.tag
//        let typingString = string
//        
//        if typingString.count > 0 && previousString.count == 0 {
//            fillTextField(text: typingString, tfIndex: txtTag)
//        } else if previousString.count > 0 {
//            fillTextField(text: typingString, tfIndex: txtTag+1)
//        }
//        
//        if typingString.count == 0 {
//            clearTextField(tfIndex: txtTag)
//        }
//        
//        return false
//    }
//    
//    func fillTextField(text: String, tfIndex: Int) {
//        if tfIndex > stackViewCodeTxt.arrangedSubviews.count {
//            return
//        }
//        var tf = view.viewWithTag(tfIndex) as! VerificationTextField
//        tf.text = text
//        
//        if tfIndex == stackViewCodeTxt.arrangedSubviews.count { return }
//        tf = view.viewWithTag(tfIndex+1) as! VerificationTextField
//        tf.becomeFirstResponder()
//    }
//    
//    func clearTextField(tfIndex: Int) {
//        if tfIndex == 0 { return }
//        var tf = view.viewWithTag(tfIndex) as! VerificationTextField
//        tf.text = ""
//        
//        if tfIndex == 1 {
//            tf = view.viewWithTag(1) as! VerificationTextField
//            tf.becomeFirstResponder()
//            return
//        }
//        tf = view.viewWithTag(tfIndex-1) as! VerificationTextField
//        tf.becomeFirstResponder()
//    }
//}
